//Modules - Encapsulated code (only share minimum)
//CommonJS , every file is module (by default)

const names = require("./4-names")
const {sayHi,sendHi} = require("./5-utils")
const data = require('./6-alternative-flavor')
require('./7-mind-grenade')
console.log(data)
sayHi(names.peter)
sayHi(names.john)
sendHi(names.john)
